VAN_MENU_ROW_TJ         equ $00ff9368
VAN_MENU_COL_TJ         equ $00ff936a
VAN_MENU_INV_POS_TJ     equ $00ff9366
VAN_PLAYER_LIVES        equ $00ffa248
VAN_PLAYER_BUCKS        equ $00ffa24a
VAN_PLAYER_POINTS       equ $00ffa24c
VAN_PLAYER_HP           equ $00ffa252
VAN_ENTITY_INFO_TABLE   equ $00ffa25a
VAN_INVENTORIES         equ $00ffdac2 ; add size of inventory for Earl's inv addr
VAN_MAP_OBJECT_TABLE    equ $00ffdae2
VAN_COLLECTED_OBJ_TABLE equ $00ffdde8
VAN_SHIP_PIECE_LEVELS   equ $00ffe212