Fn_SetRandomSeed            equ $00004ee8
Fn_OpenPresentSelectionMenu equ $00008f3a
Fn_OpenRandomizerPresent    equ $000093aa
Fn_MenuLoop                 equ $00009888
Fn_GetMaxHP                 equ $0000ae90
Fn_DropPresent              equ $00014e16
Fn_OpenPresent              equ $00016ef4
Fn_ProcessFallingTomatoes   equ $0001c52a
Fn_InitiateCupidHearts      equ $0001cb86
Fn_SayText                  equ $0001e01e
Fn_QueueDialogueSequence    equ $0001e38e
Fn_ShowCollectedShipPieces  equ $000208e4
Fn_MathAbs                  equ $0002714a
Fn_PlayPCMSound             equ $0003f5dc
Fn_PlayPSGSound             equ $0003f770

Sfx_Money                   equ $0008233c
Sfx_Eat                     equ $0004d75a

VAN_FIXED_WORLD_SHIP_PIECES equ $00097738
VAN_FOOD_TO_HP_TABLE        equ $000abe98